version: 0.0
os: linux

files:
  - source: files/
    destination: /var/www/html/node-ang-app

permissions:
    - object: /var/www/html/node-ang-app
      mode: 755
      owner: apache
      group: apache
      type:
       - directory

hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.sh
  AfterInstall:
    - location: scripts/webserver-start.sh
